config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :comments, only: [:destroy,:new,:index,:create], module: :projects
  end
  resources :users, only: [:show,:index]
  resources :comments, only: [:show,:index,:destroy]
  resources :tasks do
    resources :comments, only: [:destroy,:new,:index,:create], module: :tasks
  end
  devise_scope :user do
	  authenticated :user do
	    root 'projects#index', as: :authenticated_root
	  end
		unauthenticated do
	   root "devise/sessions#new", as: :unauthenticated_root
	  end
  end
  ## API
  namespace :api , defaults: { format: 'json' } do
    namespace :v1 do
      resources :tasks, only: [:show,:index]
      resources :projects, only: [:show,:index]
      resources :comments, only: [:show,:index]
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project, optional: true
  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, :priority, :status, :deadline_days, presence: true
  # a task can be in status out_of_date only if have init or started status before
  enum status: [:init, :started, :finish, :near_to_expired, :out_of_date]

  scope :init_tasks, -> { where(status: "init") }
  scope :terminated, -> { where("status = ? OR status = ? OR status = ?", 2, 3, 4) }

  def self.out_of_date 
    tasks = Task.where("status = ? OR status = ?", 0, 1 ) # only tasks with status init or started
    tasks.each do |t|
      !t.end_date.nil?  && t.end_date < Time.now ? t.update_column(:status, "out_of_date") : ''
    end
  end

  def self.before_expired
    tasks = Task.where("status = ? OR status = ?", 0, 1 ) # only tasks with status init or started
    tasks.each do |t|
      # check if is end_date is between time.now with deadline_days
      !t.deadline_days.nil? && t.deadline_days > 0 && !t.end_date.nil?  && t.end_date < Time.now && t.end_date > Time.now - t.deadline_days.days ? t.update_column(:status, "near_to_expired") : ''
    end
  end

end

app/controllers/api/v1/tasks_controller.rb
module Api
  module V1
    class TasksController < V1Controller

      before_action :set_task, only: [:show]

      def show
        render json: { status: :ok, task: @task}
      end

      def index
        render json: { status: :ok, tasks: Task.all}
      end

      private
      def set_task
        @task = Task.find(params[:id])
      end

    end
  end
end

app/controllers/tasks/comments_controller.rb
class Tasks::CommentsController < CommentsController
  before_action :set_commentable
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment = @comment.destroy
    respond_to do |format|
      if @comment.errors.present?
        puts ap @comment.errors.messages
        format.html { redirect_to task_url(@commentable.id) }
        format.json { head :no_content }
      else
        format.html { redirect_to task_url(@commentable.id)}
        format.json { head :no_content }
      end
    end
  end
  private
    def set_commentable
      @commentable = Task.find(params[:task_id])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update,:show, :destroy]
  load_and_authorize_resource

  def index
    current_user.has_role?(:admin) ? @tasks = Task.all : @tasks = current_user.tasks
    respond_to do |format|
      format.html
      format.json { render json: TasksDatatable.new(view_context, @tasks) }
    end
    authorize! :read, @tasks
    # https://stackoverflow.com/questions/19441188/disable-user-from-running-index-action-in-specific-controller-using-cancan-on-ra
  end

  def show
    authorize! :read, @task
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.project_id = params[:project_id] if params.has_key?(:project_id) && !params[:project_id].nil?
    @task.status = Task.statuses.key(params[:status].to_i) if params.has_key?(:status) && !params[:status].nil?
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path }
      else
        format.html { render :new }
      end
    end
  end

  def new
    @task = Task.new
  end

  def update
    respond_to do |format|
      if @task.update(task_params)  && @task.update_column(:status, params[:status])
        format.html { redirect_to tasks_path }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @task = @task.destroy 
    respond_to do |format|
      if @task.errors.present?
        puts ap @task.errors.messages
        format.html { redirect_to tasks_url }
        format.json { head :no_content }
      else
        format.html { redirect_to tasks_url}
        format.json { head :no_content }
      end
    end
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task)
          .permit(:name, :project_id, :priority, :status, :end_date, :deadline_days)
  end


end

app/views/tasks/_form.html.erb
<div class="form-group">
  <label class="col-sm-4 control-label">Name</label>
  <div class="col-sm-8">
  <%= f.input :name, input_html: { class: 'form-control' }, label: false , required: true%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">Project</label>
  <div class="col-sm-8">
  <%= select_tag 'project_id', options_for_select( current_user.projects.collect{ |p| [p.name,p.id]} ), label: false, required: false %>
  </div>
</div>

<div class="form-group">
  <label class="col-sm-4 control-label">Status</label>
  <div class="col-sm-8">
  <%= select_tag 'status', options_for_select( Task.statuses.collect{ |t| [t[0],t[1]]} ), label: false, required: false %>
  </div>
</div>

<div class="form-group">
  <label class="col-sm-4 control-label">DeadLine Days</label>
  <%= f.input :deadline_days, input_html: { class: 'form-control' }, label: false , required: true%>
</div>

<div class="form-group">
  <label class="col-sm-4 control-label">Priority</label>
  <%= f.input :priority, input_html: { class: 'form-control' }, label: false , required: true%>
</div>


<div class="form-group">
  <label class="col-sm-4 control-label">End date</label>
  <%= f.input :end_date, as: :date, html5: true %>
</div>


<div class="form-actions">
  <%= f.button :submit, class: "btn btn-success btn-sm" %>
  <%= link_to 'Back', projects_path, class: "btn btn-primary btn-sm" %>
</div>

app/views/tasks/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit task</h1>
    <%= simple_form_for([@task], wrapper: false, label: false, :method => :PATCH ) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="row">
  <% if current_user.has_role?(:admin) %>
    <h1>All Tasks</h1>
  <% else %>
    <h1>Your Tasks</h1>
  <% end %>
</div>
<%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-danger pull-left" %>
<%= link_to 'Create task', new_task_path ,class: "btn btn-success pull-left" %>

<table class="table table-title" id="tasks_datatable" data-source="<%= tasks_path(format: "json") %>">
    <thead>
      <tr>
        <th>Name</th>
        <th>Project</th>
        <th>Priority</th>
        <th>Status</th>
        <th>Deadline days</th>
        <th>End Date</th>
        <th style="width: 300px;"></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
</table>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New Task</h1>
    <%= simple_form_for([@task], wrapper: false, label: false) do |f| %>
      <%= render 'form' , f: f %>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="form-group">
  <label class="col-sm-4 control-label">Name</label>
  <div class="col-sm-8">
  <%= @task.name%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">Project</label>
  <div class="col-sm-8">
  <%= @task.project.present? ? @task.project.name : 'Doesnt Have'%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">Priority</label>
  <div class="col-sm-8">
  <%= @task.priority %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">Status</label>
  <div class="col-sm-8">
  <%= @task.status %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">DeadLine days</label>
  <div class="col-sm-8">
  <%= @task.deadline_days %>
  </div>
</div>

<div class="form-group">
  <label class="col-sm-4 control-label">End date</label>
  <%= !@task.end_date.nil? ? @task.end_date.strftime("%d-%m-%y") : 'Doesnt have' %>
</div>

<%= render partial: "comments/comments", locals: {commentable: @task} %>
<%= render partial: "comments/form", locals: {commentable: @task} %>

<div class="form-actions">
  <%= link_to 'Back', tasks_path, class: "btn btn-primary btn-sm" %>
</div>