config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :comments, only: [:destroy,:new,:index,:create], module: :projects
  end
  resources :users, only: [:show,:index]
  resources :comments, only: [:show,:index,:destroy]
  resources :tasks do
    resources :comments, only: [:destroy,:new,:index,:create], module: :tasks
  end
  devise_scope :user do
	  authenticated :user do
	    root 'projects#index', as: :authenticated_root
	  end
		unauthenticated do
	   root "devise/sessions#new", as: :unauthenticated_root
	  end
  end
  ## API
  namespace :api , defaults: { format: 'json' } do
    namespace :v1 do
      resources :tasks, only: [:show,:index]
      resources :projects, only: [:show,:index]
      resources :comments, only: [:show,:index]
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user

  validates :name, :kind, :start, presence: true
  validates_uniqueness_of :name

  enum kind: [:normal, :work, :personal, :family]

  before_create :check_dates

  def check_dates
    projects = Project.where(kind: kind).pluck(:start,:end)
    i = 0
    if start != nil && self.end != nil
      while(i < projects.size)
        if projects[i][0] != nil && projects[i][1] != nil
          (projects[i][0].to_date ... projects[i][1].to_date).include?(self.start.to_date) ? throw(:abort) : ''
          (projects[i][0].to_date ... projects[i][1].to_date).include?(self.end.to_date) ? throw(:abort) : ''
        end
        i += 1
      end
    end
  end

end

app/controllers/api/v1/projects_controller.rb
module Api
  module V1
    class ProjectsController < V1Controller
      before_action :set_project, only: [:show]

      def index
        render json: { status: :ok, projects: Project.all}
      end
      
      def show
        render json: { status: :ok, project: @project}
      end

      private
      #def project_params
      #  params.require(:project)
      #        .permit(:name, :start, :user_id)
      #end

      def set_project
        @project = Project.find(params[:id])
      end

    end
  end
end

app/controllers/projects/comments_controller.rb
class Projects::CommentsController < CommentsController
  before_action :set_commentable


  def destroy
    @comment = Comment.find(params[:id])
    @comment = @comment.destroy
    respond_to do |format|
      if @comment.errors.present?
        puts ap @comment.errors.messages
        format.html { redirect_to project_url(@commentable.id) }
        format.json { head :no_content }
      else
        format.html { redirect_to project_url(@commentable.id)}
        format.json { head :no_content }
      end
    end
  end

  private
    def set_commentable
      @commentable = Project.find(params[:project_id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :set_project, only: [:edit, :update,:show, :destroy]
  def index
    current_user.has_role?(:admin) ? @projects = Project.all : @projects = current_user.projects
    respond_to do |format|
      format.html
      format.json { render json: ProjectsDatatable.new(view_context, @projects) }
    end
  end

  def show 
    # show task with priority
    @tasks = @project.tasks.order('priority DESC')
  end

  def edit
    @tasks = Task.where(project_id: nil)
  end
  
  def create
    @project = Project.new(project_params)
    @project.kind = Project.kinds.key(params[:kind].to_i)
    @tasks = Task.where(project_id: nil)
    @project.user_id = current_user.id
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path }
      else
        @check_date =  true if @project.errors.full_messages.size == 0 # i know is not the better way but is for user can see
        format.html { render :new }
      end
    end
  end
  
  def new
    @project = Project.new
    @tasks = Task.where(project_id: nil)
  end
  
  def update
    respond_to do |format|
      new_task = Task.find(params[:task_id]) if params.has_key?(:task_id) && !params[:task_id].blank? 
      @project.tasks = @project.tasks.push(new_task) if !new_task.nil?
      if @project.update(project_params)  && @project.update_column(:kind, params[:kind])
        if !new_task.nil?
          new_task.update_column(:project_id, @project.id)
        end
        format.html { redirect_to projects_path }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @project = @project.destroy 
    respond_to do |format|
      if @project.errors.present?
        puts ap @project.errors.messages
        format.html { redirect_to projects_url }
        format.json { head :no_content }
      else
        format.html { redirect_to projects_url}
        format.json { head :no_content }
      end
    end
  end

  private
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project)
          .permit(:name, :start, :end, :user_id, :description, :kind)
  end

end

app/views/projects/_form.html.erb
<div class="form-group">
  <label class="col-sm-4 control-label">Name</label>
  <div class="col-sm-8">
  <%= f.input :name, input_html: { class: 'form-control' }, label: false , required: true%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">Description</label>
  <div class="col-sm-8">
  <%= f.input :description, input_html: { class: 'form-control' }, label: false , required: false%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">Tipo</label>
  <div class="col-sm-8">
  <%= select_tag 'kind', options_for_select( Project.kinds.collect{ |t| [t[0],t[1]]} ), label: false, required: false %>
  </div>
  </div>
  
  <div class="form-group">
  <label class="col-sm-4 control-label">Start date</label>
  <%= f.input :start, as: :date, html5: true, hint: ("probably there are overlapping projects between start date and end date" if @check_date) %>
  </div>
  
  <div class="form-group">
  <label class="col-sm-4 control-label">End date</label>
  <%= f.input :end, as: :date, html5: true %>
  </div>
  
  <div class="form-group">
  <label> Add Task</label>
  <%= select_tag 'task_id', options_for_select( @tasks.collect{ |t| [t.name,t.id]} ), label: false, required: false, :prompt => "Add a task" %>
</div>


<div class="form-actions">
  <%= f.button :submit, class: "btn btn-success btn-sm" %>
  <%= link_to 'Back', projects_path, class: "btn btn-primary btn-sm" %>
</div>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit project</h1>
    <%= simple_form_for([@project], wrapper: false, label: false, :method => :PATCH ) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="row">
  <% if current_user.has_role?(:admin) %>
    <h1>All Projects</h1>
  <% else %>
    <h1>Your Projects</h1>
  <% end %>
</div>
<%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-danger pull-left" %>
<%= link_to 'Create Project', new_project_path ,class: "btn btn-success pull-left" %>

<table class="table table-title" id="projects_datatable" data-source="<%= projects_path(format: "json") %>">
    <thead>
      <tr>
        <th>Name</th>
        <th>Kind</th>
        <th>Start</th>
        <th>End</th>
        <th>Expired</th>
        <th style="width: 300px;"></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
</table>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New project</h1>
    <%= simple_form_for([@project], wrapper: false, label: false) do |f| %>
      <%= render 'form' , f: f %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="form-group">
  <label class="col-sm-4 control-label">Name</label>
  <div class="col-sm-8">
  <%= @project.name%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">Description</label>
  <div class="col-sm-8">
  <%= @project.description%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">Type</label>
  <div class="col-sm-8">
  <%= @project.kind %>
  </div>
</div>

<div class="form-group">
  <label class="col-sm-4 control-label">Start date</label>
  <%= !@project.start.nil? ? @project.start.strftime("%d-%m-%y") : 'Doesnt have' %>
</div>

<div class="form-group">
  <label class="col-sm-4 control-label">End date</label>
  <%= !@project.end.nil? ? @project.end.strftime("%d-%m-%y") : 'Doesnt have'%>
</div>


<%= render partial: "comments/comments", locals: {commentable: @project} %>
<%= render partial: "comments/form", locals: {commentable: @project} %>


<div class="row">
  <h1>Task of the project</h1>
</div>
<table class="table table-title" >
    <thead>
      <tr>
        <th>Name</th>
        <th>Project</th>
        <th>Priority</th>
        <th>Status</th>
        <th>Deadline days</th>
        <th>End Date</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |t| %>
        <tr>
          <td><%= (t.name.present? ? t.name :  '')%> </td>
          <td><%= (t.project.present? && t.project.name.present? ? t.project.name : '' ) %> </td> 
          <td><%= (t.priority.present? ? t.priority : '' )%> </td>
          <td><%= (t.status.present? ? t.status : '' )%> </td>
          <td><%= (t.deadline_days.present? ? t.deadline_days : 'No' )%> </td>
          <td><%= (t.end_date.present? ? t.end_date.strftime("%d-%m-%y") : '' )%> </td>
        </tr>
      <% end %>
    </tbody>
</table>

<div class="form-actions">
  <%= link_to 'Back', projects_path, class: "btn btn-primary btn-sm" %>
</div>