config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :comments, only: [:destroy,:new,:index,:create], module: :projects
  end
  resources :users, only: [:show,:index]
  resources :comments, only: [:show,:index,:destroy]
  resources :tasks do
    resources :comments, only: [:destroy,:new,:index,:create], module: :tasks
  end
  devise_scope :user do
	  authenticated :user do
	    root 'projects#index', as: :authenticated_root
	  end
		unauthenticated do
	   root "devise/sessions#new", as: :unauthenticated_root
	  end
  end
  ## API
  namespace :api , defaults: { format: 'json' } do
    namespace :v1 do
      resources :tasks, only: [:show,:index]
      resources :projects, only: [:show,:index]
      resources :comments, only: [:show,:index]
    end
  end
end

app/views/layouts/_sidenav.html.erb
<div id="mySidenav" class="sidenav">
  <%= link_to 'Projects',projects_path %>
  <%= link_to 'Tasks',tasks_path %>
  <% if current_user.has_role?(:admin) %>
    <%= link_to 'Users',users_path %>
  <% end %>
  <%= link_to 'Comments',comments_path %>
</div>

<!-- Use any element to open the sidenav
<span onclick="openNav()">open</span>
-->


<!-- Add all page content inside this div if you want the side nav to push page content to the right (not used if you only want the sidenav to sit on top of the page -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="main">
    <% if !current_user.nil? %>
      <%= render "layouts/sidenav" %>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>